"""online_courses

Revision ID: 07cf281df86c
Revises: 4a8a38b59535
Create Date: 2022-11-20 12:00:51.361924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cf281df86c'
down_revision = '4a8a38b59535'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('online_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('online_courses')
    # ### end Alembic commands ###
