"""implemented_student_table

Revision ID: 4a8a38b59535
Revises: 29da9f3beb94
Create Date: 2022-11-20 11:46:04.704462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8a38b59535'
down_revision = '29da9f3beb94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('first_neme', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('pesel', sa.String(length=11), nullable=False))
    op.add_column('students', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('adress', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'students', ['pesel'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'adress')
    op.drop_column('students', 'phone')
    op.drop_column('students', 'pesel')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_neme')
    # ### end Alembic commands ###
