"""new_models

Revision ID: d3b04d4fb134
Revises: 07cf281df86c
Create Date: 2022-11-20 13:19:43.015610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b04d4fb134'
down_revision = '07cf281df86c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onside_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adress', sa.String(length=50), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('days', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_neme', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('pesel', sa.String(length=11), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('adress', sa.String(length=50), nullable=True),
    sa.Column('enrollment_data', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pesel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    op.drop_table('onside_courses')
    # ### end Alembic commands ###
